#!/bin/bash

torrentid=$1
torrentname=$2
torrentpath=$3
count=0

#change these variables according to your configuration

Dport="58846" #deluge Daemon port
logpath="~/AutoReannounce.log" #log file path


echo "${torrentname}:" >> $logpath
checktorrent=$(deluge-console "connect 127.0.0.1:${Dport}; info -v $torrentid" | grep "Tracker status" | awk -F': ' '{ print $2 }') 
while [ "$count" -lt 100 ] && [[ "$checktorrent" != "Announce OK" ]]; do
  deluge-console "connect 127.0.0.1:${Dport}; update_tracker $torrentid"
  checktorrent=$(deluge-console "connect 127.0.0.1:${Dport}; info -v $torrentid" | grep "Tracker status" | awk -F': ' '{ print $2 }')
  ((count++))
  sleep 2
done
case "$count" in
99)
  echo "  Torrent ID: ${torrentid}" >> $logpath
  echo "  Torrent Path: ${torrentpath}" >> $logpath
  echo "  Tracker status: ${checktorrent}." >> $logpath
  echo "  Re-announced 100 time(s)." >> $logpath
  exit 1
  ;;
*)
  echo "  Torrent ID: ${torrentid}" >> $logpath
  echo "  Torrent Path: ${torrentpath}" >> $logpath
  echo "  Tracker status: ${checktorrent}." >> $logpath
  echo "  Re-announced ${count} time(s)." >> $logpath
  exit 0
esac
exit 0
